Musique/Musique/Models/Music.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Musique.Models
{
    public class Music
    {
        [Required]
        public int ID { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [Range(1000, 3000)]
        public int ReleaseDate { get; set; }

        [Required]
        [StringLength(60)]
        public string Artist { get; set; }

        [Required]
        [StringLength(60)]
        public string Album { get; set; }

        [Required]
        [StringLength(30)]
        public string Genre { get; set; }

        [Required]
        [Range(1, 100)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
    }
}

Musique/Musique/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Musique.Models;
using System.Web.Security;

namespace Musique.Controllers
{
    [Authorize]
    [RequireHttps]
    public class CommentsController : Controller
    {
        private MusicDBContext db = new MusicDBContext();

        // GET: Comments
        public ActionResult Index()
        {
            return View();
        }

        // GET: Comments/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Content,Rating,MusicId")] Comment Comment)
        {
            Comment.CommentDate = DateTime.Now;
            Comment.UserName = Membership.GetUser().UserName;

            if (ModelState.IsValid)
            {
                db.Comments.Add(Comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comments/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comments/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Musique/Musique/Controllers/MusicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Musique.Models;
using Musique.ViewModels;
using Musique.Services;
using System.IO;

namespace Musique.Controllers
{
    [RequireHttps]
    public class MusicsController : Controller
    {
        private MusicDBContext db = new MusicDBContext();
        private CommentsService commentsService = new CommentsService();

        // GET: Musics
        [HttpGet]
        public ActionResult Index(MusicsResearch filters)
        {
            var musics = db.Musics.ToList();
            var filteredMusics = new List<Music>();
            filteredMusics = musics;

            if (!string.IsNullOrEmpty(filters.MusicTitle))
            {
                filteredMusics = db.Musics.Where(c => c.Title.StartsWith(filters.MusicTitle)).ToList();
            }
            if (!string.IsNullOrEmpty(filters.MusicGenre))
            {
                filteredMusics = filteredMusics.Where(c => c.Genre == filters.MusicGenre).ToList();
            }

            List<string> DiffFormats = new List<string>() { "mp3", "m4a", "wma", "wav" };

            if (filters.MusicFormatsResearch != null) {
                List<string> musiques = new List<string>();
                foreach (string f in filters.MusicFormatsResearch)
                {
                    foreach (var file in Directory.GetFiles("C:/Users/Fanny/Source/Repos/musique/Musique/Musique/Data", "*." + f))
                    {
                        musiques.Add(Path.GetFileNameWithoutExtension(file));
                    }
                }
                filteredMusics = filteredMusics.Where(c => musiques.Contains(c.Title)).ToList();
            }


            MusicsResponseVM musicsResponseVM = new MusicsResponseVM()
            {
                FilteredMusicsCounter = filteredMusics.Count(),
                MusicsCounter = musics.Count(),
                Musics = filteredMusics,
                MusicGenres = db.Musics.Select(c => c.Genre).Distinct().ToList(),
                MusicFormats = DiffFormats
            };

            return View(musicsResponseVM);
        }

        // GET: Musics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicDetailVM musicDetail = new MusicDetailVM() {
                Music = db.Musics.Find(id),
                Comments = commentsService.GetCommentsByMusicId(id)
            };
            if (musicDetail.Music == null)
            {
                return HttpNotFound();
            }
            return View(musicDetail);
        }

        // GET: Musics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Musics/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ReleaseDate,Artist,Album,Genre,Price,Formats")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Musics.Add(music);
                db.SaveChanges();
                if (Request.Files.Count > 0)
                {
                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        var file = Request.Files[i];
                        if (file != null && file.ContentLength > 0)
                        {
                            string extension = Path.GetExtension(file.FileName);
                            string format = extension.Substring(1);
                            List<string> DiffFormats = new List<string>() { "mp3", "m4a", "wma", "wav" };
                            if (DiffFormats.Contains(format))
                            {
                                string fileName = music.ID + extension;
                                var path = Path.Combine(Server.MapPath("../Data"), fileName);
                                file.SaveAs(path);
                            }
                            else
                            {
                                throw new System.ArgumentException("Format non accepté", "extension");
                            }
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            return View(music);
        }

        // GET: Musics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Musics.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Musics/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ReleaseDate,Artist,Album,Genre,Price")] Music music)
        {
            if (Request.Files.Count > 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        string extension = Path.GetExtension(file.FileName);
                        string format = extension.Substring(1);
                        List<string> DiffFormats = new List<string>() { "mp3", "m4a", "wma", "wav" };
                        if (DiffFormats.Contains(format))
                        {
                            string fileName = Request["ID"] + extension;
                            var path = Path.Combine(Server.MapPath("../Data"), fileName);
                            file.SaveAs(path);
                        }
                        else
                        {
                            throw new System.ArgumentException("Format non accepté", "extension");
                        }
                    }
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(music).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(music);
        }

        // POST: Musics/Delete/5
        [HttpPost]
        public ActionResult Delete()
        {
            string id = Request["musicID2"];
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Musics.Find(Int32.Parse(id));

            if (music == null)
            {
                return HttpNotFound();
            }
            db.Musics.Remove(music);
            db.SaveChanges();
            return PartialView("_Delete", music);
        }

        // POST: Musics/DeleteFile
        [HttpPost]
        public ActionResult DeleteFile()
        {
            string file = Request["file"];
            if (System.IO.File.Exists("C:/Users/Fanny/Source/Repos/musique/Musique/Musique/Data" + file))
            {
                System.IO.File.Delete("~/Data/" + file);
                return PartialView("_DeleteFile", file);
            }
            return PartialView("_FileNoExist", file);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Musique/Musique/Views/Musics/Create.cshtml
@model Musique.Models.Music

@{
    ViewBag.Title = "Create";
}

<h2>Ajouter une musique</h2>


@using (Html.BeginForm("Create", "Musics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="files" class="control-label col-md-2">Upload your files</label>
            <div class="col-md-10">
                <input type="file" name="files" accept=".wav,.mp3,.wma,.m4a" multiple />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Musique/Musique/Views/Musics/Delete.cshtml
@model Musique.Models.Music

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Music</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Musique/Musique/Views/Musics/Details.cshtml
@model Musique.ViewModels.MusicDetailVM

@{
    ViewBag.Title = "Details";
}

<h2>Details of @Model.Music.Title</h2>
<hr />

<div id="addedToCart">
</div>
<div id="removedFromCart">
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Music.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.Album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.Price)
        </dd>
		<dt>
			Formats
		</dt>

		<dd>
            @foreach (var file in Directory.GetFiles("C:/Users/Fanny/Source/Repos/musique/Musique/Musique/Data", Model.Music.Title + ".*"))
            {
                <p>@Path.GetExtension(file)</p>
                <audio src="~/Data/@(file)"></audio>
            }
        </dd>
    </dl>
    <p class="text-right">
        <a href="@Url.Action("Index", "Musics")" class="btn btn-warning">Back to list <span class="glyphicon glyphicon-circle-arrow-left"></span></a>
        <a href="@Url.Action("Edit", "Musics", new { id = Model.Music.ID })" class="btn btn-primary">Edit <span class="glyphicon glyphicon-pencil"></span></a>
		<button id="removeFromCartBtn" type="button" class="btn btn-danger is-hidden" value="@Model.Music.ID">Remove from cart</button>
		<button id="addToCartBtn" type="button" class="btn btn-success" value="@Model.Music.ID">Add to cart</button>
    </p>
</div>

<script type="text/javascript" defer>
	$(document).ready(function () {
		$('#addToCartBtn').on('click', function () {
			var musicIDadd = $(this).val();
			$.ajax({
				method: "POST",
				url: "/Cart/AddToCart",
				data: { musicIDadd: musicIDadd }
			}).done(function (response) {
				$('#addedToCart').html(response);
				$('#addToCartBtn').addClass('is-hidden');
				$('#removeFromCartBtn').removeClass('is-hidden');
			});
		});
		$('#removeFromCartBtn').on('click', function () {
			var musicIDrm = $(this).val();
			$.ajax({
				method: "POST",
				url: "/Cart/Delete",
				data: { musicIDrm: musicIDrm }
			}).done(function (response) {
				$('#removedFromCart').html(response);
				$('#removeFromCartBtn').addClass('is-hidden');
				$('#addToCartBtn').removeClass('is-hidden');
			});
		});
	});
</script>

<div>
@foreach (var comment in Model.Comments)
{
	<div>
		<h3>@Html.DisplayFor(modelComment => comment.UserName)</h3>
		<p>@Html.DisplayFor(modelComment => comment.Rating)</p>
		<p>@Html.DisplayFor(modelComment => comment.Content)</p>
	</div>
}
@if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
{
    <div>
    @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h4>Comment</h4>
        <div class="form-group">
            <input type="number" name="rating" class="form-control" />
            <textarea name="content" class="form-control" maxlength="1000"></textarea>
        </div>
    }
    </div>
}
</div>

Musique/Musique/Views/Musics/Edit.cshtml
@model Musique.Models.Music

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div id="deletedfile">
</div>

@using (Html.BeginForm("Edit", "Musics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Music</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

		<div class="row">
			<div class=" col-md-6">
				<div class="form-group">
					@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Album, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					<label for="files" class="control-label col-md-2">Upload your files</label>
					<div class="col-md-10">
						<input type="file" name="files" accept=".wav,.mp3,.wma,.m4a" multiple />
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<input type="submit" value="Save" class="btn btn-default" />
					</div>
				</div>
			</div>
			<div class="col-md-6">
				@foreach (var file in Directory.GetFiles("C:/Users/Fanny/Source/Repos/musique/Musique/Musique/Data", Model.ID + ".*"))
				{
					String fst = Path.GetFileNameWithoutExtension(file);
					String snd = Path.GetExtension(file);
					String title = fst + snd.Substring(1);
					<div id="@Path.GetFileName(file)">
						<div>@Path.GetExtension(file)</div>
						<a href="#" data-toggle="modal" data-target="#modaldelete@(title)">Delete</a>
						<div id="modaldelete@(title)" class="modal fade" role="dialog">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal">&times;</button>
										<h4 class="modal-title">Are you sure you want to delete this file ?</h4>
									</div>
									<div class="modal-body">
										<dl class="dl-horizontal">
											<dt>Extension</dt>

											<dd>@Path.GetExtension(file)</dd>

										</dl>
									</div>
									<div class="modal-footer">
										<button type="button" class="delete btn btn-danger" value="@Path.GetFileName(file)" data-id="@title">Delete</button>
										<button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				}
			</div>
		</div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript" defer>
	$(document).ready(function () {
		$('button.delete').on('click', function () {
			var file = $(this).val();
			var id = $(this).attr('data-id');
			$.ajax({
				method: "POST",
				url: "/Musics/DeleteFile",
				data: { file: file }
			}).done(function (response) {
				$('#deletedfile').html(response);
				$('#modaldelete' + id).modal('hide');
				$('#' + file).addClass('hidden');
			});
		});
	});
</script>

Musique/Musique/Views/Musics/_Delete.cshtml
@model Musique.Models.Music

<div class="alert alert-success alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<strong>@Model.Title</strong> has been deleted.
</div>

Musique/Musique/Views/Musics/_DeleteFile.cshtml
@model string

<div class="alert alert-success alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<strong>@Model</strong> has been deleted.
</div>

Musique/Musique/Views/Musics/_FileNoExist.cshtml
@model string

<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<strong>@Model</strong> doesn't exist.
</div>